from imod import mf6


def moderate_settings(
    modelnames: list[str] = ['imported_model'],
    print_option: str = 'summary',
    outer_csvfile: str | None = None,
    inner_csvfile: str | None = None,
    no_ptc: bool | None = None,
    outer_dvclose: float = 0.001,
    outer_maximum: int = 150,
    under_relaxation: str = 'dbd',
    under_relaxation_theta: float = 0.9,
    under_relaxation_kappa: float = 0.0001,
    under_relaxation_gamma: float = 0.0,
    under_relaxation_momentum: float = 0.0,
    backtracking_number: int = 0,
    backtracking_tolerance: float = 0.0,
    backtracking_reduction_factor: float = 0.0,
    backtracking_residual_limit: float = 0.0,
    inner_maximum: int = 30,
    inner_dvclose: float = 0.001,
    inner_rclose: float = 100.0,
    rclose_option: str = 'strict',
    linear_acceleration: str = 'bicgstab',
    relaxation_factor: float = 0.97,
    preconditioner_levels: int = 0,
    preconditioner_drop_tolerance: float = 0.0,
    number_orthogonalizations: int = 0,
):
    """Returns a mf6.Solution object with moderate settings for model solution.
    These settings are suitable for most models, but can be adjusted as needed."""

    return mf6.Solution(
        modelnames=modelnames,
        print_option=print_option,
        outer_csvfile=outer_csvfile,
        inner_csvfile=inner_csvfile,
        no_ptc=no_ptc,
        outer_dvclose=outer_dvclose,
        outer_maximum=outer_maximum,
        under_relaxation=under_relaxation,
        under_relaxation_theta=under_relaxation_theta,
        under_relaxation_kappa=under_relaxation_kappa,
        under_relaxation_gamma=under_relaxation_gamma,
        under_relaxation_momentum=under_relaxation_momentum,
        backtracking_number=backtracking_number,
        backtracking_tolerance=backtracking_tolerance,
        backtracking_reduction_factor=backtracking_reduction_factor,
        backtracking_residual_limit=backtracking_residual_limit,
        inner_maximum=inner_maximum,
        inner_dvclose=inner_dvclose,
        inner_rclose=inner_rclose,
        rclose_option=rclose_option,
        linear_acceleration=linear_acceleration,
        relaxation_factor=relaxation_factor,
        preconditioner_levels=preconditioner_levels,
        preconditioner_drop_tolerance=preconditioner_drop_tolerance,
        number_orthogonalizations=number_orthogonalizations,
    )
